docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - { Intro: intro.md }
    - Reference:
      - 'Standard Filters': standard-filters.md
      - 'Word Filters': word.md
      - 'File Filters': file.md
      - 'Filter Chains': filter-chains.md
      - 'String Inflection': inflector.md
      - 'Static Filter': static-filter.md
      - 'Writing Filters': writing-filters.md
site_name: laminas-filter
site_description: Laminas\Filter
repo_url: 'https://github.com/laminas/laminas-filter'
