docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - 'Standard Filters': standard-filters.md
      - 'Word Filters': word.md
      - 'File Filters': file.md
      - 'Filter Chains': filter-chains.md
      - 'String Inflection': inflector.md
      - 'Static Filter': static-filter.md
      - 'Writing Filters': writing-filters.md
site_name: zend-filter
site_description: "Programmatically filter and normalize data and files."
repo_url: 'https://github.com/zendframework/zend-filter'
